print(terminalTextColorGreen .. [[   _____ ______  _____  _____ __   __     ______  _____  _   _  _   _  _____ ___  ___ _____ ]])
print(terminalTextColorYellow .. [[  |  _  || ___ \|_   _||_   _|\ \ / /     |  _  \|  ___|| | | || | | ||  _  ||  \/  ||  ___|]])
print(terminalTextColorGreen .. [[  | | | || |_/ /  | |    | |   \ V /      | | | || |__  | | | || |_| || | | || .  . || |__  ]])
print(terminalTextColorBlue .. [[  | | | ||  __/   | |    | |   /   \      | | | ||  __| | | | ||  _  || | | || |\/| ||  __| ]])
print(terminalTextColorRed .. [[  \ \_/ /| |      | |   _| |_ / /^\ \     | |/ / | |___ \ \_/ /| | | |\ \_/ /| |  | || |___ ]])
print(terminalTextColorBlue .. [[   \___/ \_|      \_/   \___/ \/   \/     |___/  \____/  \___/ \_| |_/ \___/ \_|  |_/\____/ ]] .. terminalTextColorReset)
print(terminalTextColorGreen .. [[_____ ______  _____  _____ __   __     ______  _____  _   _  _   _  _____ ___  ___ _____ ]])
print(terminalTextColorYellow .. [[|  _  || ___ \|_   _||_   _|\ \ / /     |  _  \|  ___|| | | || | | ||  _  ||  \/  ||  ___|]])
print(terminalTextColorGreen .. [[| | | || |_/ /  | |    | |   \ V /      | | | || |__  | | | || |_| || | | || .  . || |__  ]])
print(terminalTextColorBlue .. [[| | | ||  __/   | |    | |   /   \      | | | ||  __| | | | ||  _  || | | || |\/| ||  __| ]])
print(terminalTextColorRed .. [[\ \_/ /| |      | |   _| |_ / /^\ \     | |/ / | |___ \ \_/ /| | | |\ \_/ /| |  | || |___ ]])
print(terminalTextColorBlue .. [[ \___/ \_|      \_/   \___/ \/   \/     |___/  \____/  \___/ \_| |_/ \___/ \_|  |_/\____/ ]] .. terminalTextColorReset)
print("")
print("")
print(terminalTextColorBold .. "v0.0.4" .. terminalTextColorReset)
print("")
print("")